name: rust-tooling
repository: 42bytelabs/rust-tooling
version: 0.1.2

ecosystems:
  - Docs
  - Rust
  - Containers

# locations:
#   - name: "Docs"
#     ecosystem: "Docs"
#     paths:
#       - README.md
#     patterns:
#       - 'uses:\s+{repository}/publish@v{version}'

