name: "Release"

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: "Version Bump"
        options: 
          - patch
          - minor
          - major

permissions:
  contents: read

jobs:
  project:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/project.yml
    uses: 42ByteLabs/.github/.github/workflows/project.yml@main
    secrets: inherit

  container:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/container.yml
    uses: 42ByteLabs/.github/.github/workflows/container.yml@main
    if: ${{ needs.project.outputs.release == 'true' }}
    needs: [ project ]
    secrets: inherit
    permissions:
      id-token: write
      contents: write
      packages: write
      security-events: write
      attestations: write
    with:
      version: ${{ needs.project.outputs.version }}
      container-name: "42bytelabs/rust-tooling"
      docker-file: "./Dockerfile"

