name: Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}
  schedule:
    - cron: '0 14 * * 2'

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  semgrep:
    # https://github.com/42ByteLabs/.github/blob/main/.github/workflows/semgrep.yml
    uses: 42ByteLabs/.github/.github/workflows/semgrep.yml@main
    secrets: inherit
